version: "3.8"

services:
  migrations:
    container_name: "shop_migrations"
    build:
      context: .
      dockerfile: migrations/Dockerfile
    command: python -m migrations
    volumes:
      - ".:/opt:rw"
    env_file:
      - ".env"
    depends_on:
      - db

  shop:
    container_name: "shop"
    build:
      context: .
      dockerfile: shop/Dockerfile
    command: python -m shop
    restart: always
    ports:
      - "81:80"
    volumes:
      - "./src:/opt/src:ro"
      - "./shop:/opt/shop:ro"
      - "./migrations:/opt/migrations:rw"
      - "./alembic.ini:/opt/alembic.ini:ro"
    env_file:
      - ".env"
    depends_on:
      - db

  db:
    container_name: "shop_db"
    image: postgres:16-alpine3.19
    hostname: "shop_db"
    restart: always
    env_file:
      - ".env"
    ports:
      - "5432:5432"