version: "3.8"

services:
  migrations:
    container_name: "shop_migrations"
    build:
      context: .
      dockerfile: migrations/Dockerfile
    command: python -m migrations
    volumes:
      - ".:/opt:rw"
    env_file:
      - ".env"
    depends_on:
      - db
      -
  shop:
    container_name: "shop"
    build:
      context: .
      dockerfile: shop/Dockerfile
    command: python -m shop
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./src:/opt/src:ro"
      - "./shop:/opt/shop:ro"
    env_file:
      - ".env"
    depends_on:
      - db

  db:
    container_name: "shop_db"
    image: postgres:16-alpine3.19
    hostname: "shop_db"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
