"""empty message

Revision ID: caa63490f4de
Revises: 
Create Date: 2024-03-17 03:40:42.254297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa63490f4de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_department',
    sa.Column('dep_name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dep_name')
    )
    op.create_table('shop_man',
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=40), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=12), nullable=True),
    sa.Column('date_add', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('shop_sales_man',
    sa.Column('man_id', sa.INTEGER(), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['shop_department.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['man_id'], ['shop_man.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('man_id', 'department_id', 'id')
    )
    op.create_index(op.f('ix_shop_sales_man_department_id'), 'shop_sales_man', ['department_id'], unique=False)
    op.create_index(op.f('ix_shop_sales_man_man_id'), 'shop_sales_man', ['man_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_sales_man_man_id'), table_name='shop_sales_man')
    op.drop_index(op.f('ix_shop_sales_man_department_id'), table_name='shop_sales_man')
    op.drop_table('shop_sales_man')
    op.drop_table('shop_man')
    op.drop_table('shop_department')
    # ### end Alembic commands ###
